### ISSUE TITLE
量化的一些疑问

### ISSUE THREAD

**Issue by zyt1024** [androny1012/HLS_MNIST#1]
```bash
Sequential(
  (0): Quantize(scale=tensor([0.0079]), zero_point=tensor([0]), dtype=torch.quint8)
  (1): Net(
    (conv1): QuantizedConv2d(1, 8, kernel_size=(3, 3), stride=(1, 1), scale=0.06916582584381104, zero_point=46, bias=False)
    (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (conv2): QuantizedConv2d(8, 8, kernel_size=(3, 3), stride=(1, 1), scale=0.39073848724365234, zero_point=84, bias=False)
    (fc1): QuantizedLinear(in_features=200, out_features=10, scale=0.7683325409889221, zero_point=75, qscheme=torch.per_tensor_affine)
    (relu): ReLU()
  )
  (2): DeQuantize()
)
```
我看上面的`scale=0.06916582584381104, zero_point=46`, 
在 [2.3_quant_test_scale_zp.py](https://github.com/androny1012/HLS_MNIST/blob/main/src/sw/py_prj/toolchain_conv/2.3_quant_test_scale_zp.py)中这个有`scale=20697`，还多了个`conv1_shift`，请问一下这个为什么要这样做啊，怎么计算这个scale和shift呀。
``` python
    conv1_scale = 20697
    conv1_shift = 9
    conv1_zp    = 46
```

**Comment by androny1012** [comment]
看起来你自己解决了，软件量化的结果确实是scale=0.06916582584381104, zero_point=46，但这个没办法直接在硬件里实现，所以进行了转换代码在2.1_get_quant_para.py

**Comment by zyt1024** [comment]
是的，我看到转换代码了，另外，大佬的代码中,没有使用  `quant_model.qconfig=torch.quantization.get_default_qconfig('fbgemm')`，如果使用这个进行量化，采用的我看是每个channel的量化，这种的话，后面获取参数的逻辑是需要变的吧，硬件实现是不是也会变得复杂：
``` python
    quant_model.qconfig = torch.quantization.default_qconfig
    # quant_model.qconfig = torch.quantization.get_default_qconfig('fbgemm')
    quant_model=torch.quantization.prepare(quant_model, inplace=True)
```

**Comment by zyt1024** [comment]
> 看起来你自己解决了，软件量化的结果确实是scale=0.06916582584381104, zero_point=46，但这个没办法直接在硬件里实现，所以进行了转换代码在2.1_get_quant_para.py

请教一个问题，望大佬解答，大佬给的案例中卷积算子的`bias=False`,我将`bias=True`,使用`pytroch`默认的量化配置，`bias`是不给量化的，还是`float`类型，这种情况怎么办？有好的解决办法嘛？

**Comment by androny1012** [comment]
> 是的，我看到转换代码了，另外，大佬的代码中,没有使用 `quant_model.qconfig=torch.quantization.get_default_qconfig('fbgemm')`，如果使用这个进行量化，采用的我看是每个channel的量化，这种的话，后面获取参数的逻辑是需要变的吧，硬件实现是不是也会变得复杂：
> 
> ```python
>     quant_model.qconfig = torch.quantization.default_qconfig
>     # quant_model.qconfig = torch.quantization.get_default_qconfig('fbgemm')
>     quant_model=torch.quantization.prepare(quant_model, inplace=True)
> ```

呃，没想这么多呢，用另一个好像跑不通，就注释掉了，这个对应的硬件实现参考的是https://github.com/adamgallas/fpga_accelerator_yolov3tiny
